from django.urls import path

from .views import (
    AssetApprovalActionView,
    AssetApprovalQueueView,
    AssetApprovalRequestView,
    AssetCreateView,
    AssetDetailView,
    AssetExportView,
    AssetImportView,
    AssetImportTemplateView,
    AssetEditView,
    AssetListView,
    AssetOverviewView,
    AssetOSCreateView,
    AssetOSUpdateView,
    AssetPortCreateView,
    AssetPortInterfaceCreateView,
    AssetPortInterfaceUpdateView,
    AssetPortUpdateView,
    AssetQuickPortInterfaceView,
    GuestApprovalListView,
    GuestApproveView,
    GuestRejectView,
    GuestSelfRegisterView,
    HomeView,
    OSCatalogView,
    LocationDetailView,
    LocationDetailLegacyRedirectView,
    LocationTreeView,
    UserDetailView,
    UserListView,
)

app_name = "inventory"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("os/", OSCatalogView.as_view(), name="os-catalog"),
    path("locations/", LocationTreeView.as_view(), name="location-tree"),
    path("locations/<int:pk>/<slug:slug>/", LocationDetailView.as_view(), name="location-detail"),
    path("locations/<int:pk>/", LocationDetailLegacyRedirectView.as_view(), name="location-detail-legacy"),
    path("asset/", AssetListView.as_view(), name="asset-list"),
    path("asset/create/", AssetCreateView.as_view(), name="asset-create"),
    path("asset/export/", AssetExportView.as_view(), name="asset-export"),
    path("asset/import/", AssetImportView.as_view(), name="asset-import"),
    path("asset/import/template/", AssetImportTemplateView.as_view(), name="asset-import-template"),
    path("asset/<int:pk>/", AssetDetailView.as_view(), name="asset-detail"),
    path("asset/<int:pk>/edit/", AssetEditView.as_view(), name="asset-edit"),
    path("asset/<int:pk>/os/add/", AssetOSCreateView.as_view(), name="asset-os-add"),
    path("asset/<int:pk>/os/<int:os_id>/update/", AssetOSUpdateView.as_view(), name="asset-os-update"),
    path("asset/<int:pk>/port/add/", AssetPortCreateView.as_view(), name="asset-port-add"),
    path("asset/<int:pk>/port/<int:port_id>/update/", AssetPortUpdateView.as_view(), name="asset-port-update"),
    path(
        "asset/<int:pk>/port/<int:port_id>/interface/add/",
        AssetPortInterfaceCreateView.as_view(),
        name="asset-port-interface-add",
    ),
    path(
        "asset/<int:pk>/port/<int:port_id>/interface/<int:interface_id>/update/",
        AssetPortInterfaceUpdateView.as_view(),
        name="asset-port-interface-update",
    ),
    path("asset/<int:pk>/quick-port-interface/", AssetQuickPortInterfaceView.as_view(), name="asset-quick-port-interface"),
    path("asset/<int:pk>/request-approval/", AssetApprovalRequestView.as_view(), name="asset-request-approval"),
    path("asset/approvals/", AssetApprovalQueueView.as_view(), name="asset-approval-queue"),
    path("asset/approvals/<int:pk>/action/", AssetApprovalActionView.as_view(), name="asset-approval-action"),
    path("asset/overview/", AssetOverviewView.as_view(), name="asset-overview"),
    path("guest/register/", GuestSelfRegisterView.as_view(), name="guest-register"),
    path("guest/approvals/", GuestApprovalListView.as_view(), name="guest-approvals"),
    path("guest/<int:pk>/approve/", GuestApproveView.as_view(), name="guest-approve"),
    path("guest/<int:pk>/reject/", GuestRejectView.as_view(), name="guest-reject"),
    path("user/", UserListView.as_view(), name="user-list"),
    path("user/<int:pk>/", UserDetailView.as_view(), name="user-detail"),
]
