# Generated by Django 6.0.2 on 2026-02-06 23:41

import django.db.models.deletion
import django.utils.timezone
import inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('vlan_id', models.PositiveIntegerField(blank=True, null=True)),
                ('cidr', models.CharField(max_length=43)),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('dhcp_enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OSFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('vendor', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('asset_type', models.CharField(choices=[('COMPUTER', 'Computer'), ('MONITOR', 'Monitor'), ('KEYBOARD', 'Keyboard'), ('PRINTER', 'Printer'), ('OTHER', 'Other')], default='COMPUTER', max_length=20)),
                ('asset_tag', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('STORED', 'Stored'), ('RETIRED', 'Retired'), ('LOST', 'Lost')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=120)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[inventory.models.validate_mac])),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='inventory.asset')),
            ],
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.GenericIPAddressField(protocol='IPv4')),
                ('status', models.CharField(choices=[('STATIC', 'Static'), ('DHCP_RESERVED', 'DHCP Reserved'), ('DHCP_DYNAMIC', 'DHCP Dynamic'), ('DEPRECATED', 'Deprecated')], default='STATIC', max_length=20)),
                ('hostname', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='inventory.network')),
                ('assigned_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_addresses', to='inventory.networkinterface')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_vlan_id', models.PositiveIntegerField(blank=True, null=True)),
                ('admins', models.ManyToManyField(blank=True, related_name='asset_admin_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='asset_member_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuestDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('mac_address', models.CharField(max_length=17, validators=[inventory.models.validate_mac])),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('enabled', models.BooleanField(default=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsored_guest_devices', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='guest_devices', to='inventory.organizationalgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='assets', to='inventory.organizationalgroup'),
        ),
        migrations.CreateModel(
            name='OSVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='inventory.osfamily')),
            ],
        ),
        migrations.CreateModel(
            name='AssetOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_os', to='inventory.asset')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.osfamily')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.osversion')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('port_kind', models.CharField(choices=[('RJ45', 'RJ45'), ('SFP', 'SFP'), ('WIFI', 'WiFi'), ('VIRTUAL', 'Virtual'), ('OTHER', 'Other')], default='RJ45', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='inventory.asset')),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ports', to='inventory.networkinterface')),
            ],
        ),
        migrations.AddConstraint(
            model_name='networkinterface',
            constraint=models.UniqueConstraint(fields=('asset', 'identifier'), name='uniq_asset_interface_identifier'),
        ),
        migrations.AddConstraint(
            model_name='ipaddress',
            constraint=models.UniqueConstraint(fields=('network', 'address'), name='uniq_network_ip_address'),
        ),
        migrations.AddConstraint(
            model_name='ipaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('assigned_interface__isnull', False)), fields=('network', 'assigned_interface'), name='uniq_active_ip_per_network_interface'),
        ),
        migrations.AddConstraint(
            model_name='osversion',
            constraint=models.UniqueConstraint(fields=('family', 'version'), name='uniq_os_family_version'),
        ),
        migrations.AddConstraint(
            model_name='port',
            constraint=models.UniqueConstraint(fields=('asset', 'name'), name='uniq_asset_port_name'),
        ),
    ]
