# Generated by Django 6.0.2 on 2026-02-07 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetos',
            name='auto_updates_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assetos',
            name='installed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetos',
            name='patch_level',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='assetos',
            name='support_state',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('SUPPORTED', 'Supported'), ('EXTENDED', 'Extended'), ('EOL', 'End of life')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='port_interfaces', to='inventory.port'),
        ),
        migrations.AddField(
            model_name='osfamily',
            name='platform_type',
            field=models.CharField(choices=[('DESKTOP', 'Desktop'), ('SERVER', 'Server'), ('MOBILE', 'Mobile'), ('OTHER', 'Other')], default='DESKTOP', max_length=20),
        ),
        migrations.AddField(
            model_name='osfamily',
            name='supports_domain_join',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='osversion',
            name='codename',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='osversion',
            name='end_of_support_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osversion',
            name='is_lts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='osversion',
            name='kernel_version',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='osversion',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
