# Generated by Django 6.0.2 on 2026-02-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_assetos_auto_updates_enabled_assetos_installed_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinterface',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='port',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
