# Generated by Django 6.0.2 on 2026-02-07 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_networkinterface_active_port_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='interface',
        ),
    ]
