# Generated by Django 6.0.2 on 2026-02-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_port_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
