# Generated by Django 6.0.2 on 2026-02-07 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_asset_name'),
        ('inventory', '0006_user_email_identity'),
    ]

    operations = [
    ]
