# Generated by Django 6.0.2 on 2026-02-08 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_guestdevice_workflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetos',
            options={'ordering': ('-id',)},
        ),
    ]
