# Generated by Django 6.0.2 on 2026-02-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_assetos_options'),
        ('inventory', '0013_location_tree_asset_location'),
    ]

    operations = [
    ]
