# Generated by Django 6.0.2 on 2026-02-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_location_slug'),
        ('inventory', '0014_merge_20260208_0935'),
    ]

    operations = [
    ]
