# Generated by Django 6.0.2 on 2026-02-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_location_path_cache'),
        ('inventory', '0015_merge_0014_location_slug_0014_merge_20260208_0935'),
    ]

    operations = [
    ]
