# Generated by Django 6.0.2 on 2026-02-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_merge_20260208_0944'),
        ('inventory', '0016_os_catalog_refactor'),
    ]

    operations = [
    ]
