# Generated by Django 6.0.2 on 2026-02-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_merge_20260208_1034'),
        ('inventory', '0017_osfamily_support_status'),
    ]

    operations = [
    ]
