# Generated by Django 6.0.2 on 2026-02-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_merge_20260208_1042'),
        ('inventory', '0018_osfamily_expand_family_types'),
    ]

    operations = [
    ]
