# Generated by Django 6.0.2 on 2026-02-17 11:06

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_merge_20260208_1347'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AssetTypeLifetime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('COMPUTER', 'Computer'), ('NOTEBOOK', 'Notebook'), ('SERVER', 'Server'), ('MONITOR', 'Monitor'), ('KEYBOARD', 'Keyboard'), ('DEVICE', 'Device'), ('NETWORK', 'Network'), ('PRINTER', 'Printer'), ('MOBILE', 'Mobile'), ('TABLET', 'Tablet'), ('BYOD', 'BYOD'), ('OTHER', 'Other')], max_length=20, unique=True)),
                ('planned_lifetime_months', models.PositiveIntegerField(help_text='Default lifetime in months')),
            ],
            options={
                'ordering': ('asset_type',),
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='commissioning_date',
            field=models.DateField(blank=True, null=True, verbose_name='Commissioning date'),
        ),
        migrations.AddField(
            model_name='asset',
            name='lifetime_override_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lifetime override (months)'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('STORED', 'Stored'), ('SPARE', 'Spare'), ('RETIRED', 'Retired'), ('DISCARDED', 'Discarded'), ('LOST', 'Lost')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetos',
            name='version',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='assets', to='inventory.assettag'),
        ),
        migrations.CreateModel(
            name='HistoricalAsset',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('asset_type', models.CharField(choices=[('COMPUTER', 'Computer'), ('NOTEBOOK', 'Notebook'), ('SERVER', 'Server'), ('MONITOR', 'Monitor'), ('KEYBOARD', 'Keyboard'), ('DEVICE', 'Device'), ('NETWORK', 'Network'), ('PRINTER', 'Printer'), ('MOBILE', 'Mobile'), ('TABLET', 'Tablet'), ('BYOD', 'BYOD'), ('OTHER', 'Other')], default='COMPUTER', max_length=20)),
                ('asset_tag', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('STORED', 'Stored'), ('SPARE', 'Spare'), ('RETIRED', 'Retired'), ('DISCARDED', 'Discarded'), ('LOST', 'Lost')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('commissioning_date', models.DateField(blank=True, null=True, verbose_name='Commissioning date')),
                ('lifetime_override_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Lifetime override (months)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.location')),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical asset',
                'verbose_name_plural': 'historical assets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NetworkApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='inventory.asset')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_approval_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
    ]
