# Generated by Django 6.0.2 on 2026-02-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last seen'),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last seen'),
        ),
    ]
