# Generated by Django 6.0.2 on 2026-02-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_taskrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='osfamily',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
